Update patch set 1
Patch Set 1:

Breaks the build on Mako

external/tinycompress/compress.c: In function 'compress_set_next_track_param':
external/tinycompress/compress.c:582:26: error: 'SNDRV_COMPRESS_SET_NEXT_TRACK_PARAM' undeclared (first use in this function)
  if (ioctl(compress->fd, SNDRV_COMPRESS_SET_NEXT_TRACK_PARAM, codec_options))

Patch-set: 1
Reviewer: Gerrit User 1000196 <1000196@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=0